name: Test and Build
on:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          cache: 'true'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build MyTemplate.sln -c Release --no-restore
      - name: Test
        run: dotnet test MyTemplate.sln --no-build
